steps:
    # Step 1: Access the secret and create auth.json
    - id: 'create-auth-json'
      name: 'gcr.io/cloud-builders/gcloud'
      entrypoint: 'bash'
      args:
          - '-c'
          - |
              gcloud secrets versions access latest --secret=october-cms-auth > auth.json
              echo "Content of auth.json (for debugging, remove in production):"
              cat auth.json

    # Step 2: Build Docker image
    - id: 'build-docker-image'
      name: 'gcr.io/cloud-builders/docker'
      entrypoint: 'bash'
      args:
          - '-c'
          - |
              echo "Building Docker image..."
              docker build -t us-central1-docker.pkg.dev/shred-index-social-login/shredindex-repo/backend:$BUILD_ID \
              --build-arg OCTOBER_CMS_AUTH="$$(cat auth.json)" \
              --progress=plain \
              .

    # Step 3: Push Docker image to Container Registry
    - id: 'push-docker-image'
      name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'us-central1-docker.pkg.dev/shred-index-social-login/shredindex-repo/backend:$BUILD_ID']

    # Step 4: Deploy container image to Cloud Run
    - id: 'deploy-to-cloud-run'
      name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
      entrypoint: gcloud
      args:
          - 'run'
          - 'deploy'
          - 'backend'
          - '--image'
          - 'us-central1-docker.pkg.dev/shred-index-social-login/shredindex-repo/backend:$BUILD_ID'
          - '--region'
          - 'us-central1'
          - '--platform'
          - 'managed'
          - '--allow-unauthenticated'
          - '--add-cloudsql-instances'
          - 'shred-index-social-login:us-central1:shredindex'
    # Step 5: Run artisan commands in CI/CD
    - id: 'ci-run-artisan'
      name: 'gcr.io/cloud-builders/docker'
      args:
          - 'run'
          - '--rm'
          - '-e'
          - 'APP_ENV=production'
          - 'us-central1-docker.pkg.dev/shred-index-social-login/shredindex-repo/backend:$BUILD_ID'
          - '/bin/sh'
          - '-c'
          - |
            echo "Running Laravel setup and migrations..."
            php artisan config:cache
            php artisan cache:clear
            php artisan config:clear
            php artisan view:clear
            php artisan october:migrate
            echo "Setup complete."
options:
    env:
        - 'START_STEP=create-auth-json'  # Set this to the ID of the step you want to start from