<?php

namespace Underflip\Resorts\Classes;

class ContinentService
{
    public function continentLookup()
    {
    return $continentLookup = [
        'AF' => 'AS', // Afghanistan
        'AL' => 'EU', // Albania
        'DZ' => 'AF', // Algeria
        'AS' => 'OC', // American Samoa
        'AD' => 'EU', // Andorra
        'AO' => 'AF', // Angola
        'AI' => 'NA', // Anguilla
        'AQ' => 'AN', // Antarctica
        'AG' => 'NA', // Antigua and Barbuda
        'AR' => 'SA', // Argentina
        'AM' => 'EU', // Armenia (also sometimes considered part of Asia)
        'AW' => 'NA', // Aruba
        'AU' => 'OC', // Australia
        'AT' => 'EU', // Austria
        'AZ' => 'EU', // Azerbaijan (also sometimes considered part of Asia)
        'BS' => 'NA', // Bahamas
        'BH' => 'AS', // Bahrain
        'BD' => 'AS', // Bangladesh
        'BB' => 'NA', // Barbados
        'BY' => 'EU', // Belarus
        'BE' => 'EU', // Belgium
        'BZ' => 'NA', // Belize
        'BJ' => 'AF', // Benin
        'BM' => 'NA', // Bermuda
        'BT' => 'AS', // Bhutan
        'BO' => 'SA', // Bolivia
        'BA' => 'EU', // Bosnia and Herzegovina
        'BW' => 'AF', // Botswana
        'BV' => 'AN', // Bouvet Island
        'BR' => 'SA', // Brazil
        'IO' => 'AS', // British Indian Ocean Territory
        'BN' => 'AS', // Brunei Darussalam
        'BG' => 'EU', // Bulgaria
        'BF' => 'AF', // Burkina Faso
        'BI' => 'AF', // Burundi
        'KH' => 'AS', // Cambodia
        'CM' => 'AF', // Cameroon
        'CA' => 'NA', // Canada
        'CV' => 'AF', // Cape Verde
        'KY' => 'NA', // Cayman Islands
        'CF' => 'AF', // Central African Republic
        'TD' => 'AF', // Chad
        'CL' => 'SA', // Chile
        'CN' => 'AS', // China
        'CX' => 'AS', // Christmas Island
        'CC' => 'AS', // Cocos (Keeling) Islands
        'CO' => 'SA', // Colombia
        'KM' => 'AF', // Comoros
        'CG' => 'AF', // Congo
        'CD' => 'AF', // Congo, The Democratic Republic of the
        'CK' => 'OC', // Cook Islands
        'CR' => 'NA', // Costa Rica
        'CI' => 'AF', // Cote D'Ivoire
        'HR' => 'EU', // Croatia
        'CU' => 'NA', // Cuba
        'CY' => 'EU', // Cyprus
        'CZ' => 'EU', // Czech Republic
        'DK' => 'EU', // Denmark
        'DJ' => 'AF', // Djibouti
        'DM' => 'NA', // Dominica
        'DO' => 'NA', // Dominican Republic
        'EC' => 'SA', // Ecuador
        'EG' => 'AF', // Egypt
        'SV' => 'NA', // El Salvador
        'GQ' => 'AF', // Equatorial Guinea
        'ER' => 'AF', // Eritrea
        'EE' => 'EU', // Estonia
        'ET' => 'AF', // Ethiopia
        'FK' => 'SA', // Falkland Islands (Malvinas)
        'FO' => 'EU', // Faroe Islands
        'FJ' => 'OC', // Fiji
        'FI' => 'EU', // Finland
        'FR' => 'EU', // France
        'GF' => 'SA', // French Guiana
        'PF' => 'OC', // French Polynesia
        'TF' => 'AN', // French Southern Territories
        'GA' => 'AF', // Gabon
        'GM' => 'AF', // Gambia
        'GE' => 'EU', // Georgia
        'DE' => 'EU', // Germany
        'GH' => 'AF', // Ghana
        'GI' => 'EU', // Gibraltar
        'GR' => 'EU', // Greece
        'GL' => 'NA', // Greenland
        'GD' => 'NA', // Grenada
        'GP' => 'NA', // Guadeloupe
        'GU' => 'OC', // Guam
        'GT' => 'NA', // Guatemala
        'GG' => 'EU', // Guernsey
        'GN' => 'AF', // Guinea
        'GW' => 'AF', // Guinea-Bissau
        'GY' => 'SA', // Guyana
        'HT' => 'NA', // Haiti
        'HM' => 'AN', // Heard Island and McDonald Islands
        'VA' => 'EU', // Holy See (Vatican City State)
        'HN' => 'NA', // Honduras
        'HK' => 'AS', // Hong Kong
        'HU' => 'EU', // Hungary
        'IS' => 'EU', // Iceland
        'IN' => 'AS', // India
        'ID' => 'AS', // Indonesia
        'IR' => 'AS', // Iran, Islamic Republic of
        'IQ' => 'AS', // Iraq
        'IE' => 'EU', // Ireland
        'IM' => 'EU', // Isle of Man
        'IL' => 'AS', // Israel
        'IT' => 'EU', // Italy
        'JM' => 'NA', // Jamaica
        'JP' => 'AS', // Japan
        'JE' => 'EU', // Jersey
        'JO' => 'AS', // Jordan
        'KZ' => 'AS', // Kazakhstan
        'KE' => 'AF', // Kenya
        'KI' => 'OC', // Kiribati
        'KP' => 'AS', // Korea, Democratic People's Republic of
        'KR' => 'AS', // Korea, Republic of
        'XK' => 'EU', // Kosovo
        'KW' => 'AS', // Kuwait
        'KG' => 'AS', // Kyrgyzstan
        'LA' => 'AS', // Lao People's Democratic Republic
        'LV' => 'EU', // Latvia
        'LB' => 'AS', // Lebanon
        'LS' => 'AF', // Lesotho
        'LR' => 'AF', // Liberia
        'LY' => 'AF', // Libya
        'LI' => 'EU', // Liechtenstein
        'LT' => 'EU', // Lithuania
        'LU' => 'EU', // Luxembourg
        'MO' => 'AS', // Macao
        'MG' => 'AF', // Madagascar
        'MW' => 'AF', // Malawi
        'MY' => 'AS', // Malaysia
        'MV' => 'AS', // Maldives
        'ML' => 'AF', // Mali
        'MT' => 'EU', // Malta
        'MH' => 'OC', // Marshall Islands
        'MQ' => 'NA', // Martinique
        'MR' => 'AF', // Mauritania
        'MU' => 'AF', // Mauritius
        'YT' => 'AF', // Mayotte
        'MX' => 'NA', // Mexico
        'FM' => 'OC', // Micronesia, Federated States of
        'MD' => 'EU', // Moldova, Republic of
        'MC' => 'EU', // Monaco
        'MN' => 'AS', // Mongolia
        'ME' => 'EU', // Montenegro
        'MS' => 'NA', // Montserrat
        'MA' => 'AF', // Morocco
        'MZ' => 'AF', // Mozambique
        'MM' => 'AS', // Myanmar
        'NA' => 'AF', // Namibia
        'NR' => 'OC', // Nauru
        'NP' => 'AS', // Nepal
        'NL' => 'EU', // Netherlands
        'NC' => 'OC', // New Caledonia
        'NZ' => 'OC', // New Zealand
        'NI' => 'NA', // Nicaragua
        'NE' => 'AF', // Niger
        'NG' => 'AF', // Nigeria
        'NU' => 'OC', // Niue
        'NF' => 'OC', // Norfolk Island
        'MP' => 'OC', // Northern Mariana Islands
        'NO' => 'EU', // Norway
        'OM' => 'AS', // Oman
        'PK' => 'AS', // Pakistan
        'PW' => 'OC', // Palau
        'PS' => 'AS', // Palestinian Territory, Occupied
        'PA' => 'NA', // Panama
        'PG' => 'OC', // Papua New Guinea
        'PY' => 'SA', // Paraguay
        'PE' => 'SA', // Peru
        'PH' => 'AS', // Philippines
        'PN' => 'OC', // Pitcairn
        'PL' => 'EU', // Poland
        'PT' => 'EU', // Portugal
        'PR' => 'NA', // Puerto Rico
        'QA' => 'AS', // Qatar
        'RE' => 'AF', // Reunion
        'RO' => 'EU', // Romania
        'RU' => 'EU', // Russian Federation (partially in Asia)
        'RW' => 'AF', // Rwanda
        'BL' => 'NA', // Saint Barthelemy
        'SH' => 'AF', // Saint Helena
        'KN' => 'NA', // Saint Kitts and Nevis
        'LC' => 'NA', // Saint Lucia
        'MF' => 'NA', // Saint Martin (French part)
        'PM' => 'NA', // Saint Pierre and Miquelon
        'VC' => 'NA', // Saint Vincent and the Grenadines
        'WS' => 'OC', // Samoa
        'SM' => 'EU', // San Marino
        'ST' => 'AF', // Sao Tome and Principe
        'SA' => 'AS', // Saudi Arabia
        'SN' => 'AF', // Senegal
        'RS' => 'EU', // Serbia
        'SC' => 'AF', // Seychelles
        'SL' => 'AF', // Sierra Leone
        'SG' => 'AS', // Singapore
        'SX' => 'NA', // Sint Maarten (Dutch part)
        'SK' => 'EU', // Slovakia
        'SI' => 'EU', // Slovenia
        'SB' => 'OC', // Solomon Islands
        'SO' => 'AF', // Somalia
        'ZA' => 'AF', // South Africa
        'GS' => 'AN', // South Georgia and the South Sandwich Islands
        'SS' => 'AF', // South Sudan
        'ES' => 'EU', // Spain
        'LK' => 'AS', // Sri Lanka
        'SD' => 'AF', // Sudan
        'SR' => 'SA', // Suriname
        'SJ' => 'EU', // Svalbard and Jan Mayen
        'SZ' => 'AF', // Swaziland
        'SE' => 'EU', // Sweden
        'CH' => 'EU', // Switzerland
        'SY' => 'AS', // Syrian Arab Republic
        'TW' => 'AS', // Taiwan
        'TJ' => 'AS', // Tajikistan
        'TZ' => 'AF', // Tanzania, United Republic of
        'TH' => 'AS', // Thailand
        'TL' => 'AS', // Timor-Leste
        'TG' => 'AF', // Togo
        'TK' => 'OC', // Tokelau
        'TO' => 'OC', // Tonga
        'TT' => 'NA', // Trinidad and Tobago
        'TN' => 'AF', // Tunisia
        'TR' => 'EU', // Turkey (partially in Asia)
        'TM' => 'AS', // Turkmenistan
        'TC' => 'NA', // Turks and Caicos Islands
        'TV' => 'OC', // Tuvalu
        'UG' => 'AF', // Uganda
        'UA' => 'EU', // Ukraine
        'AE' => 'AS', // United Arab Emirates
        'GB' => 'EU', // United Kingdom
        'US' => 'NA', // United States
        'UM' => 'OC', // United States Minor Outlying Islands
        'UY' => 'SA', // Uruguay
        'UZ' => 'AS', // Uzbekistan
        'VU' => 'OC', // Vanuatu
        'VE' => 'SA', // Venezuela
        'VN' => 'AS', // Vietnam
        'VG' => 'NA', // Virgin Islands, British
        'VI' => 'NA', // Virgin Islands, U.S.
        'WF' => 'OC', // Wallis and Futuna
        'EH' => 'AF', // Western Sahara
        'YE' => 'AS', // Yemen
        'ZM' => 'AF', // Zambia
        'ZW' => 'AF'  // Zimbabwe
        ];
    }
    public function getContinentCode(string $countryCode): ?string
    {

    $continentLookup = $this->continentLookup(); // Get the lookup array

    if (array_key_exists($countryCode, $continentLookup)) {
        return $continentLookup[$countryCode]; // Return the continent code
    } else {
        // Handle missing country code, e.g., log error, return null
        return null;
    }
    }
}
