# ===================================
#  Form Behavior Config
# ===================================

name: Site Groups
form: ~/modules/system/models/sitegroup/fields.yaml
modelClass: System\Models\SiteGroup
defaultRedirect: system/sitegroups

design:
    displayMode: basic
    size: 950

create:
    redirect: system/sitegroups/update/:id
    redirectClose: system/sitegroups

update:
    redirect: system/sitegroups
    redirectClose: system/sitegroups
