version: '3'
services:
    php:
        container_name: shredindex-backend-php
        build:
            context: ./php
        ports:
            - 9000:9000
        volumes:
            - ../:/var/www/html
            - /infrastructure/
            - ./etc/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
            - ./etc/php/conf.d/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
        environment:
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            XDEBUG_MODE: ${XDEBUG_MODE}
    mysql:
        container_name: shredindex-backend-mysql
        image: mysql:5.7
        command: mysqld --default-authentication-plugin=mysql_native_password
        ports:
            - 3306:3306
        depends_on:
            - php
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    nginx:
        container_name: shredindex-backend-nginx
        image: nginx:latest
        volumes:
            - ../:/var/www/html
            - /infrastructure/
            - ./etc/nginx/conf.d/:/etc/nginx/conf.d/
            - ./var/log/nginx/:/var/log/nginx/
        command: /bin/sh -c "envsubst '$$VIRTUAL_HOST' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        environment:
            VIRTUAL_HOST: ${VIRTUAL_HOST}
            VIRTUAL_PORT: ${VIRTUAL_PORT}
        depends_on:
            - php
        ports:
            - 80
networks:
    default:
        external:
            name: ${DEFAULT_EXTERNAL_NETWORK_NAME}
