version: 2.1

orbs:
    codecov: codecov/codecov@1.1.0

jobs:
    build-and-test:
        machine: true
        working_directory: ~/project
        steps:
            - checkout
            - run:
                name: Preparing environment from repository
                command: |
                    mv .circleci/.env.circleci .env
                    mv .infrastructure/.env.dist .infrastructure/.env
                    mv .infrastructure/docker-compose.yml.dist .infrastructure/docker-compose.yml
                    mv .infrastructure/etc/nginx/conf.d/default.conf.dist .infrastructure/etc/nginx/conf.d/default.conf
                    cp .env.dist .env
            - restore_cache:
                keys:
                    - v2-composer-{{ checksum "composer.lock" }}
            - run:
                name: docker-compose
                command: cd .infrastructure/ && docker compose down && docker compose build --no-cache && docker compose up -d && docker compose version && docker compose ps
            - run:
                name: composer install
                command: docker exec shredindex-backend-php composer install -n --prefer-dist
            - save_cache:
                key: v2-composer-{{ checksum "composer.lock" }}
                paths:
                    - vendor
            - run:
                name: Waiting for MySQL to warm up
                command: sleep 10
            - run:
                name: Check environment
                command:  |
                    docker exec shredindex-backend-php php -v
                    docker exec shredindex-backend-mysql mysql --version
            - run:
                name: Spin up October CMS
                command:  |
                    docker exec shredindex-backend-php php artisan october:migrate
                    docker exec shredindex-backend-mysql mysql -u user -ppass -e 'use shredindex; select * from underflip_resorts_resorts;'
            - run:
                name: Running PHPUnit tests
                command: docker exec shredindex-backend-php vendor/bin/phpunit --configuration plugins/underflip/resorts/phpunit.xml --coverage-clover ../../../coverage/clover.xml
            - codecov/upload:
                file: ./coverage/clover.xml

workflows:
    build-and-test:
        jobs:
            - build-and-test
