# ===================================
#  Form Behavior Config
# ===================================

name: "Template"
form: ~/modules/system/models/mailtemplate/fields.yaml
modelClass: System\Models\MailTemplate
defaultRedirect: system/mailtemplates

create:
    redirect: system/mailtemplates/update/:id
    redirectClose: system/mailtemplates

update:
    redirect: system/mailtemplates
    redirectClose: system/mailtemplates
