# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: "Event Log"

# Model Form Field configuration
form: ~/modules/cms/models/themelog/fields.yaml

# Model Class name
modelClass: Cms\Models\ThemeLog

# Default redirect location
defaultRedirect: cms/themelogs

# Preview page
preview:
    title: cms::lang.theme_log.preview_title