# ===================================
#  Configures the graph list widget
# ===================================

titleProperty: 'title'
descriptionProperty: description
descriptionProperties:
    fileName: 'File'
noRecordsMessage: 'nocio.headstart::lang.graph.no_list_records'
deleteConfirmation: 'nocio.headstart::lang.graph.delete_confirm_multiple'
itemType: graph
sortingProperties:
    url: 'cms::lang.page.url'
    title: 'cms::lang.page.title'
    fileName: 'cms::lang.page.file_name'
