# ===================================
#  List Behavior Config
# ===================================

title: "Event Log"
list: ~/modules/system/models/eventlog/columns.yaml
filter: ~/modules/system/models/eventlog/scopes.yaml
modelClass: System\Models\EventLog
recordUrl: system/eventlogs/preview/:id
noRecordsMessage: backend::lang.list.no_records
recordsPerPage: 30
showSetup: true
showCheckboxes: true
defaultSort:
    column: created_at
    direction: desc

toolbar:
    buttons: list_toolbar
    search:
        prompt: backend::lang.list.search_prompt

